apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: suilens-2206083584
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: orders
            - name: POSTGRES_PASSWORD
              value: orders
            - name: POSTGRES_DB
              value: orders
          volumeMounts:
            - name: order-pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: order-pgdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: suilens-2206083584
spec:
  selector:
    app: order-db
  ports:
    - port: 5432
      targetPort: 5432
